node_js:
- 6
- 7
language: node_js
sudo: false
script:
- npm run lint
- npm run test-cov
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: AviGZKkdKngkde6rMqzr9MJHAAb/wcC3/jOWOH1Plb4RF1D80iDZO/+5j9u6d7RuEJAxCxDLyqSxRGV2YnRvuAElFVWzS6la8q8UN95+ABTq00yYnC3XZ97N4RUxVuutYxPGAY2x2E820g8II5Va60Wb6RrbF8c2Zmn6iWLOdFuOe+xIkdCkb9QOpig6A484bKxSYNtTxUh3l6yDQSERSIY4QNA4uUwr82gsUNwFFQQtKY45hgim5FJoFZOhPT/RvncOL1PaI0w+sjwbv0odAGd0S/88T0LE2lEb5nFGOo5zGpPgKkheiJwBkx3lo6/uvGMVJ2EhfjXzT8w+rQJSLdxn5eB+L9d2MMCWeqOW3slOsgf9LFt49D/88x4Fgj5IdU4z2fWYjl6vm1EG/uct95hmLKIHDJCxuzHC/lkSPT7Frlz+Hnhs4qZy/qR/dz32FdtNMQrwzbonMYeSFrmd/pcdweZNAoWUe9NI1ObTEqpy946Wqcgyu5BzjMuhK/B1eeNqGay/yZ98QS/vvPIrSPJ5/eNtH2wuiq2IabvXfS9teiSTG+k/0aY3G2xAzKm2Gy6Z0KjhPsr4zc6Y9ucQ5E+EGNNLeruc2pW2sWeyj8d4fmCofw+KouYfY2GmnBsWbL10JyyyoF0vlIVj+vYqQH3XEIWqqfiPwssltddonCE=
